name: "OpenID Connect Conformity Tests"

on:
  pull_request:
    branches:
      - canonical

jobs:
  oidc-conformity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          repository: cybozu-go/hydra
          ref: cybozu
      - uses: actions/setup-go@v2
        with:
          go-version: "1.21"
      - name: Update fosite
        run: |
          go mod edit -replace github.com/ory/fosite=github.com/canonical/fosite@${{ github.event.pull_request.head.sha }}
          go mod tidy
      - name: Start service
        run: ./test/conformance/start.sh
      - name: Run tests
        run: ./test/conformance/test.sh -v -short -parallel 16
